version: '3.1'

services:
  dns-proxy:
    build: .
    restart: always
    environment:
        # time in miliseconds
      PRONSY_CACHEENABLED: true
      PRONSY_CACHETTL: 120
      PRONSY_RESOLVERTIMEOUT: 3000
      PRONSY_TCPMAXCONNPOOL: 100
      PRONSY_UDPMAXQUEUESIZE: 1000
        # google
     #PRONSY_PROVIDERHOST: 8.8.8.8
        # dns.sb
     #PRONSY_PROVIDERHOST: 185.222.222.222
        # CloudFlare
      PRONSY_PROVIDERHOST: 1.1.1.1
      PRONSY_PROVIDERPORT: 853
      PRONSY_PORT: 5353
    ports:
      - "5353:5353/tcp"
      - "5353:5353/udp"
      - "8080:8080"
